services:
  backend:
    build:
      context: ../..
      dockerfile: ./Dockerfile.prod
    image: backend_app:prod
    container_name: backend_app
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      BASE_URL: http://127.0.0.1:3001
      DATABASE_URL: postgresql://postgres:mypassword@my_postgres:5432/app_ga
      JWT_SECRET: OFWUkMsv9nF6Z5kuIxFXfgQGKNaGR4jaYe0wlBhWV78=
      JWT_SECRET_REFRESH: shEsWQr2qtD89HLOBc9eTnQB1EQagWry8Wq75eGbWFI=

networks:
  ga_network:
    external: true
